name: ronin-install.sh

on:
  push:
    paths:
      - .github/workflows/ronin-install.yml
      - Makefile
      - ronin-install.sh
      - test/helper.sh
      - test/ronin_install_test.sh
  pull_request:
    paths:
      - .github/workflows/ronin-install.yml
      - Makefile
      - ronin-install.sh
      - test/helper.sh
      - test/ronin_install_test.sh

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: "ronin-install.sh on Ubuntu"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update -qq -y && sudo apt-get install -qq -y shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    name: "ronin-install.sh on Fedora Linux"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dnf update -q -y && dnf install -q -y shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  opensuse:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    name: "ronin-install.sh on OpenSUSE"
    steps:
      - name: Install dependencies
        run: zypper ref && zypper --non-interactive in tar gzip findutils shunit2
      - uses: actions/checkout@v4
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    name: "ronin-install.sh on ArchLinux"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman-key --init && \
          pacman -Syu --noconfirm && \
          pacman -Sy --noconfirm git base base-devel && \
          useradd -d /home/makepkg makepkg && \
          mkdir -p /home/makepkg/{.config/pacman,.gnupg,out} && \
          chown -R makepkg:users /home/makepkg && \
          sudo -u makepkg /bin/bash -c "cd /home/makepkg && git clone --quiet --depth 1 https://aur.archlinux.org/shunit2.git && cd shunit2/ && makepkg" && \
          pacman -U --noconfirm /home/makepkg/shunit2/shunit2-*.pkg.tar.zst
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  macos:
    runs-on: macos-latest
    name: "ronin-install.sh on macOS"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  freebsd:
    runs-on: ubuntu-latest
    name: "ronin-install.sh on FreeBSD"
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      id: freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y shunit2
        run: |
          export SHUNIT2="$(command -v shunit2 2>/dev/null)"
          ./test/ronin_install_test.sh

  openbsd:
    runs-on: ubuntu-latest
    name: "ronin-install.sh on OpenBSD"
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      id: openbsd
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add bash shunit2
        run: |
          export SHUNIT2="$(command -v shunit2 2>/dev/null)"
          ./test/ronin_install_test.sh
